#!/usr/bin/env bash
set -e
sudo -v

sudo update-grub

sudo apt update
sudo apt install -y `paste -d ' ' -s  packages-minimal`

curl -O "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt install -f -y

curl -O "https://use.fontawesome.com/releases/v5.2.0/fontawesome-free-5.2.0-web.zip"
unzip -o fontawesome-free-5.2.0-web.zip
mkdir -p ~/.fonts
cp fontawesome-free-5.2.0-web/webfonts/*.ttf ~/.fonts/
fc-cache -f -v fc-list | grep -i "awe"
