#!/usr/bin/env bash

set -e

sudo -v
sudo apt update
sudo apt install -qy $(paste -d ' ' -s packages)

TEMP_DIR="$(mktemp -d -t dotfiles.XXX)"
curl -s "https://use.fontawesome.com/releases/v5.3.1/fontawesome-free-5.3.1-desktop.zip" -o "${TEMP_DIR}/fa.zip"
unzip -q "${TEMP_DIR}/fa.zip" -d ${TEMP_DIR}
mkdir -p ~/.fonts
cp "${TEMP_DIR}"/fontawesome-free-5.3.1-desktop/otfs/*  ~/.fonts
rm -rf "${TEMP_DIR}"

stow -Rv -t ~ home
sudo stow -Rv -t /etc etc
