#!/usr/bin/env bash
set -e
DOTFILES=$(cd "$(dirname "$0")" && pwd)

# Install vscode extensions
# https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
if command -v code >/dev/null; then
  for EXT in $(paste -d ' ' -s ${DOTFILES}/vscode-extensions); do
    code --install-extension ${EXT} --force
  done;
else
  echo "vscode is not installed, ignoring"
fi
