#!/usr/bin/env bash
set -e

TEMP_DIR=${1}
TEMP_ZIP=${TEMP_DIR}/1password.zip

curl \
  -s "https://cache.agilebits.com/dist/1P/op/pkg/v0.5.3/op_linux_amd64_v0.5.3.zip" \
  -o ${TEMP_ZIP}
unzip -q ${TEMP_ZIP} -d ${TEMP_DIR}
mkdir -p ~/.local/bin
mv ${TEMP_DIR}/op ~/.local/bin/
