#!/usr/bin/env bash
set -e

TEMP_DIR=${1}
TEMP_ZIP=${TEMP_DIR}/fontawesome.zip

curl \
  -s "https://fontawesome.com/v4.7.0/assets/font-awesome-4.7.0.zip" \
  -o ${TEMP_ZIP}
unzip -q ${TEMP_ZIP} -d ${TEMP_DIR}
mkdir -p ~/.fonts
cp ${TEMP_DIR}/font-awesome-4.7.0/fonts/*.ttf  ~/.fonts
